global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'opendif-core'
    environment: 'local'

scrape_configs:
  # Exchange Services
  - job_name: orchestration-engine
    metrics_path: /metrics
    static_configs:
      - targets:
          - orchestration-engine:4000
        labels:
          service: 'orchestration-engine'
          port: '4000'

  - job_name: consent-engine
    metrics_path: /metrics
    static_configs:
      - targets:
          - consent-engine:8081
        labels:
          service: 'consent-engine'
          port: '8081'

  - job_name: policy-decision-point
    metrics_path: /metrics
    static_configs:
      - targets:
          - policy-decision-point:8082
        labels:
          service: 'policy-decision-point'
          port: '8082'

  # Root Level Services
  - job_name: portal-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - portal-backend:3000
        labels:
          service: 'portal-backend'
          port: '3000'

